---
abstract: 'Perl DateTime extension for computing the sunrise/sunset on a given day'
author:
  - 'Ron Hill <rkhill@firstlight.net>'
  - 'Jean Forget <JFORGET@cpan.org>'
build_requires:
  DateTime::Duration: 0
  DateTime::Span: 0
  DateTime::SpanSet: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTime-Event-Sunrise
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  DateTime: 0.21
  DateTime::Set: 0.16
  Math::Trig: 0
  POSIX: 0
  Params::Validate: 0
  Set::Infinite: 0
version: 0.0503
